# Generated by Django 5.2 on 2025-04-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="yes",
            field=models.BooleanField(default=False),
        ),
    ]
