# Generated by Django 5.2 on 2025-04-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0006_product_yes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="yes",
        ),
    ]
