# Generated by Django 5.2 on 2025-04-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
        ("product_module", "0007_remove_product_yes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="module_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="engine.module",
            ),
            preserve_default=False,
        ),
    ]
